apiVersion: v1
kind: Namespace
metadata:
  name: javascript-namespace
  labels:
    name: javascript-namespace
    environment: production
    security.policy: restricted
  annotations:
    security.alpha.kubernetes.io/sysctls: "net.core.somaxconn=65535"
    security.alpha.kubernetes.io/seccomp: "runtime/default"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: javascript-resource-quota
  namespace: javascript-namespace
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "0"
    pods: "10"
    services: "5"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: javascript-limit-range
  namespace: javascript-namespace
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "1Gi"
    type: PersistentVolumeClaim
