apiVersion: v1
kind: Secret
metadata:
  name: javascript-app-secrets
  namespace: javascript-namespace
  labels:
    app: javascript-app
    environment: production
type: Opaque
data:
  # Base64 encoded secrets (replace with actual values)
  # Example: echo -n "your-secret-key" | base64
  SESSION_SECRET: "eW91ci1zZXNzaW9uLXNlY3JldC1rZXk="  # your-session-secret-key
  API_KEY: "eW91ci1hcGkta2V5LWhlcmU="              # your-api-key-here
  DATABASE_PASSWORD: "eW91ci1kYXRhYmFzZS1wYXNzd29yZA=="  # your-database-password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javascript-app-sa
  namespace: javascript-namespace
  labels:
    app: javascript-app
    environment: production
  annotations:
    # IAM role for service account (if using cloud provider)
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/IAM-ROLE-NAME
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: javascript-app-role
  namespace: javascript-namespace
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: javascript-app-rolebinding
  namespace: javascript-namespace
subjects:
- kind: ServiceAccount
  name: javascript-app-sa
  namespace: javascript-namespace
roleRef:
  kind: Role
  name: javascript-app-role
  apiGroup: rbac.authorization.k8s.io
